server:
  shutdown: graceful
  tomcat:
    threads:
      max: 200 # 최대 워커 스레드 수 (default : 200)
      min-spare: 10 # 최소 유지 스레드 수 (default : 10)
    connection-timeout: 1m # 연결 타임아웃 (ms) (default : 60000ms = 1m)
    max-connections: 8192 # 최대 동시 연결 수 (default : 8192)
    accept-count: 100 # 대기 큐 크기 (default : 100)
    keep-alive-timeout: 60s # 60s
  max-http-request-header-size: 8KB

spring:
  main:
    web-application-type: servlet
  application:
    name: commerce-api
  profiles:
    active: local
  config:
    import:
      - jpa.yml
      - logging.yml
      - monitoring.yml
      - redis.yml

springdoc:
  use-fqn: true
  swagger-ui:
    path: /swagger-ui.html

datasource:
  mysql-jpa:
    main:
      jdbc-url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/loopers
      username: ${MYSQL_USER:application}
      password: "${MYSQL_PWD:application}"
  redis:
    database: 0
    master:
      host: ${REDIS_MASTER_HOST:localhost}
      port: ${REDIS_MASTER_PORT:6379}
    replicas:
      - host: ${REDIS_REPLICA_HOST:localhost}
        port: ${REDIS_REPLICA_PORT:6380}

---
spring.config.activate.on-profile: local, test

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: qa

---
spring.config.activate.on-profile: prd

springdoc:
  api-docs:
    enabled: false

---
spring.config.activate.on-profile: docker

datasource:
  mysql-jpa:
    main:
      jdbc-url: jdbc:mysql://mysql:3306/loopers
      username: application
      password: application

  redis:
    master:
      host: redis-master
      port: 6379
    replicas:
      - host: redis-readonly
        port: 6379